const GET_USER = "GET_USER";
const IS_LOGIN = "IS_LOGGED_IN";
const IS_LOGIN_ERROR = "IS_LOGGED_IN_ERROR";
const SIGN_UP_USER = "SIGN_UP_USER";
const SIGN_UP_USER_ERROR = "SIGN_UP_USER_ERROR";
const SIGN_OUT_USER = "SIGN_OUT_USER";
const SIGN_OUT_USER_ERROR = "SIGN_OUT_USER_ERROR";
const READ_POSTS = "READ_POSTS";
const READ_POSTS_ERROR = "READ_POSTS_ERROR";
const ADD_POST = "ADD_POST";
const LIKE_POST = "LIKE_POST";
const COMMENTS = "COMMENTS";
const COMMENT_ON_POST = "COMMENT_ON_POST";
const SUGGESTED_FRIENDS = "SUGGESTED_FRIENDS";
const SUGGESTED_FRIENDS_ERROR = "SUGGESTED_FRIENDS_ERROR";
const GET_USER_PROFILE = "GET_USER_PROFILE";
const GET_USER_PROFILE_ERROR = "GET_USER_PROFILE_ERROR";
export {
  GET_USER,
  IS_LOGIN,
  IS_LOGIN_ERROR,
  SIGN_UP_USER,
  SIGN_UP_USER_ERROR,
  SIGN_OUT_USER,
  SIGN_OUT_USER_ERROR,
  READ_POSTS,
  READ_POSTS_ERROR,
  ADD_POST,
  LIKE_POST,
  COMMENTS,
  COMMENT_ON_POST,
  SUGGESTED_FRIENDS,
  SUGGESTED_FRIENDS_ERROR,
  GET_USER_PROFILE,
  GET_USER_PROFILE_ERROR
};
